geofood/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.rest_list, name='rest_list'),
    url(r'^info/(?P<pk>\d+)/$', views.rest_detail, name='rest_detail'),
    url(r'^info/new/$', views.rest_new, name='rest_new'),
    url(r'^info/edit/(?P<pk>\d+)$', views.rest_edit, name='rest_edit'),
    url(r'^info/remove/(?P<pk>\d+)$', views.rest_remove, name='rest_remove')
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

from mysite.views import home, UserRegister, UserRegisterDone

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rest/', include('geofood.urls', namespace='rest')),
    url(r'^$', home, name='home'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page':'/'}),
    url(r'^acounts/register/$', UserRegister.as_view(), name='register'),
    url(r'^ accounts/register/done$', UserRegisterDone.as_view(), name='register_done'),
]

geofood/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    groop = models.CharField(max_length=50)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Restaurant(models.Model):
    lon = models.FloatField()
    lat = models.FloatField()
    zoom = models.PositiveSmallIntegerField(default=14)
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, null=True, blank=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    author = models.ForeignKey('auth.User')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Restaurant)
    # 카테고리가 free인 경우 : 등록대기
    category = models.ForeignKey(Category, null=True, blank=True)

    def __str__(self):
        return self.text[:50]

geofood/forms.py
from django import forms

from geofood.models import Post, Restaurant



class PostForm(forms.ModelForm):

    class Meta:
        model= Post
        fields= ('text', 'author')

class RestForm(forms.ModelForm):

    class Meta:
        model= Restaurant
        fields= ('lon', 'lat', 'title', 'category')

geofood/views.py
from django.shortcuts import render

from geofood.models import Restaurant, Category

from django.shortcuts import redirect, get_object_or_404

from geofood.forms import PostForm, RestForm
# Create your views here.

def rest_list(request):
    food = Category.objects.all()
    ctgry = request.GET.get('category')
    if ctgry != None:
        posts = Restaurant.objects.filter(category__name = ctgry)
    else:
        posts = Restaurant.objects.all()

    return render(request, 'rest/rest_list.html', {'food':food,'posts':posts})


def rest_detail(request, pk):
    rest = get_object_or_404(Restaurant, pk=pk)
    return render(request, 'rest/rest_detail.html', {'rest':rest})


def rest_new(request):
    if request.method == 'POST':
        form = RestForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            return redirect('rest:rest_detail', pk=post.pk)
    else:
        form = RestForm()
        postForm = PostForm()
    return render(request, 'rest/rest_edit.html', {'form': form, 'postform': postForm})


def rest_edit(request,pk):
    post = get_object_or_404(Restaurant, pk=pk)
    if request.method == 'POST':
        form = RestForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            return redirect('rest:rest_detail', pk=post.pk)
    else:
        form = RestForm(instance=post)
        postForm =PostForm(instance=post)
    return render(request, 'rest/rest_edit.html', {'form': form, 'postform': postForm})


def rest_remove(request,pk):
    post = get_object_or_404(Restaurant, pk=pk)
    post.delete()
    return redirect('rest:rest_list')

mysite/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from geofood.models import Restaurant, Category

def home(request):
    food = Category.objects.all()
    return render(request, 'home.html', {'food':food})

class UserRegister(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserRegisterDone(TemplateView):
    template_name = 'registration/register_done.html'

geofood/templates/rest/base.html
{% extends 'base.html' %}
{% block sub-content %}

{% block title %}
{% endblock %}


{% block rest %}
{% endblock %}

{% endblock %}

geofood/templates/rest/rest_detail.html
{% extends 'rest/base.html' %}

{% block rest %}

<div>
    <h2>{{ rest }}<a href="{% url 'rest:rest_edit' pk=rest.pk %}">수정하기</a> <a href="{% url 'rest:rest_remove' pk=rest.pk %}">[삭제]</a></h2>
</div>
<button onclick="showPosition()">위치보기</button>


<div id="mapholder"></div>

<script src="https://maps.google.com/maps/api/js?key=AIzaSyAgNvEgXFWJdohNBo48ZWFNef4M8YUsx2Q"></script>

<script>


        function showPosition() {
            var lat = {{ rest.lat }};
            var lon = {{ rest.lon }};
            var latlon = new google.maps.LatLng(lat, lon)
            var mapholder = document.getElementById('mapholder')
            mapholder.style.height = '250px';
            mapholder.style.width = '500px';

            var myOptions = {
            center:latlon,zoom:{{ rest.zoom }},
            mapTypeId:google.maps.MapTypeId.ROADMAP,
            mapTypeControl:false,
            navigationControlOptions:{style:google.maps.NavigationControlStyle.SMALL}
            }

            var map = new google.maps.Map(document.getElementById("mapholder"), myOptions);
            var marker = new google.maps.Marker({position:latlon,map:map,title:"You are here!"});
        }

        function showError(error) {
            switch(error.code) {
                case error.PERMISSION_DENIED:
                    x.innerHTML = "User denied the request for Geolocation."
                    break;
                case error.POSITION_UNAVAILABLE:
                    x.innerHTML = "Location information is unavailable."
                    break;
                case error.TIMEOUT:
                    x.innerHTML = "The request to get user location timed out."
                    break;
                case error.UNKNOWN_ERROR:
                    x.innerHTML = "An unknown error occurred."
                    break;
            }
        }
</script>

{% endblock %}

geofood/templates/rest/rest_edit.html
{% extends 'rest/base.html' %}

{% block rest %}
<div>
    <h1>새글쓰기</h1>
    <form action="" method="POST">
	    {% csrf_token %}
		{{ postform.as_p }}
	    {{ form.as_p }}
	    <button type="submit">저장</button>
	</form>
</div>

{% endblock %}

geofood/templates/rest/rest_list.html
{% extends 'rest/base.html' %}

{% block rest %}

{% for post in posts %}
    <div>
        <h3><a href="{% url 'rest:rest_detail' pk=post.pk %}">{{ post }}</a></h3>
    </div>
{% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body onload="showPosition()">
    <div>
        <div>
            {% block title %}
            {% endblock %}
        </div>
    </div>
    <h1><a href="/">나는 알고 너는 모르는 맛집[홈으로]</a></h1>
    <!--<p><a href="/">Home 바로가기</a></p>-->
    <p><a href="{% url 'rest:rest_new' %}">새글쓰기</a></p>
    <p><a href="{% url 'rest:rest_list' %}">전체보기</a></p>
    {% for food in food %}
    <a href="{% url 'rest:rest_list' %}?category={{ food }}">{{ food }}</a>
    {% endfor %}

    {% if user.is_authenticated %}
    <h3>{{ user.username }} 님 안녕하세요.</h3>
    <nav>
        <a href="{% url 'password_change' %}">비밀번호 변경</a>
        <a href="{% url 'logout' %}">Logout</a>
        {% else %}
        <p><a href="{% url 'login' %}">Login</a></p>
        <p><a href="{% url 'register' %}">회원가입</a></p>

    </nav>
    {% endif %}
    {% block register %}
    {% endblock %}

    {% block home %}
    {% endblock %}

    {% block sub-content %}
    {% endblock%}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block home %}

{% endblock %}